import { Palette } from "std-widgets.slint";
import { ChatView, ChatMessageFormat, ChatMessage, ChatMessageListView, ChatMessageInputView } from "widgets/chat/ChatView.slint";

export { ChatView, ChatMessageFormat, ChatMessage, ChatMessageListView, ChatMessageInputView }

export component ApplicationWindow inherits Window {
    preferred-width: 700px;
    preferred-height: 500px;
    title: "Little Boat";

    main-view := ChatView {}

}