[workspace]
resolver = "2"
members = [
	"little-boat-client"
]

default-members = [
  "little-boat-client"
]

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
codegen-units = 1
lto = true

[workspace.dependencies]



[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.87"
authors=["Hash2000 <infinitehash@yandex.ru>"]
categories=["tools"]
repository = "https://github.com/hash2000/mp-little-boat-rs"
license = "MPL-2.0"