[workspace]
resolver = "2"
members = [
	"little-boat-client", 
	"little-boat-core",
]

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
codegen-units = 1
lto = true

[workspace.dependencies]
# logs
log = "0.4.27"
env_logger = "0.11.8"

# errors 
thiserror = "2"
anyhow = "1.0.100"

# key-value embedded database
sled = "0.34.7"

# async
async-trait = "0.1.88"
futures = "0.3.31"
tokio-test = "0.4"
tokio-stream = "0.1.17"
tokio-tungstenite = "0.27.0"
tokio = { version = "1.47.1", features = [
	"full"
] }

# desktop UI


## parsers tokenizers
# markdown parser
pulldown-cmark = "0.13.0"

# json
simd-json = "0.16.0"
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"

# connectivity
webrtc = "0.14.0"

rand = "0.9.2"
tempfile = "3.22.0"
directories-next = "2.0.0"
generic-array = "1.2.0"
uuid = "1.17.0"
bytes = "1.10.1"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.87"
authors = ["Hash2000 <infinitehash@yandex.ru>"]
categories = [
	"tools",
	"chat"
]
repository = "https://github.com/hash2000/mp-little-boat-rs"
license = "AGPL-3.0"

