[package]
name = "little-boat-client-term"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
categories.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
ratatui.workspace = true
crossterm.workspace = true
anyhow.workspace = true

