import { Button, VerticalBox } from "std-widgets.slint";
import { SideBar } from "MainMenu/SideBar.slint";

export component ApplicationWindow inherits Window {
    preferred-width: 700px;
    preferred-height: 500px;
    title: "Little Boat";

    HorizontalLayout {
        side-bar := SideBar {
            title: "Main menu";
            model: [
                "test1",
                "test2"
            ];
        }
    }
}