[package]
name = "little-boat-client"
default-run = "little-boat-client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
categories.workspace = true
repository.workspace = true

[[bin]]
name = "little-boat-client"
path = "src/main.rs"

[dependencies]
little-boat-core = { path = "../little-boat-core" }
litle-boat-widgets = { path = "../little-boat-widgets" }

anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
tokio.workspace = true

simd-json.workspace = true
pulldown-cmark.workspace = true

iced.workspace = true
iced.features = ["highlighter", "tokio", "debug"]