[package]
name = "little-boat-client"
default-run = "little-boat-client"
build = "src/build.rs"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
categories.workspace = true
repository.workspace = true

[[bin]]
name = "little-boat-client"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.45.1", features = [
	"rt", 
	"rt-multi-thread",
	"io-util",
	"io-std",
	"time", 
	"process",
	"macros",
	"fs",
	"parking_lot"
] }
slint = "1.12.0"

[build-dependencies]
slint-build = "1.12"