import { TabWidget, HorizontalBox, StyleMetrics, Palette, Button } from "std-widgets.slint";
import { ChatGroupSideBar } from "ChatGroupSideBar.slint";

export component ChatView {
    preferred-height: 100%;
    preferred-width: 100%;

    forward-focus: focus-scope;
    focus-scope := FocusScope { }

    Rectangle {
        background: Palette.background;

        HorizontalLayout {
            chat-side-bar := ChatGroupSideBar {
                selected(item, index) => {
                    
                }
            }
            
            Button {
                text: "Add goup";
                clicked => {
                    
                }
            }
        }
    }
}