import { TabWidget, HorizontalBox, StyleMetrics, Palette, Button, TextEdit, ScrollView, VerticalBox, ListView } from "std-widgets.slint";
import { ChatGroupSideBar } from "ChatGroupSideBar.slint";
import { FontSettings } from "../../Styles.slint";

export enum ChatMessageFormat {
    Markdown
}

export enum ChatMessageContentType {
    Text,
    Citation,
    Image,
    Heading,
}

export struct ChatMessageContentItem {
    data: string,
    content-type: ChatMessageContentType,
    font-size-mul: length,
}

export struct ChatMessage {
    id: string,
    sender: string,
    content-raw: string,
    content: [ChatMessageContentItem],
    format: ChatMessageFormat,
}

export global ChatViewAdapter {
    in-out property <[ChatMessage]> messages;
    pure callback message(msg: string);
}

export component ChatMessageListView {
    VerticalLayout {
        ListView {
            for message[message_index] in ChatViewAdapter.messages: Rectangle {
                clip: true;
                max-width: 100px;
                min-height: FontSettings.body.font-size;
                background: #227bc0;
                border-radius: 5px;
                padding: 5px;

                VerticalLayout {
                    padding: 5px;

                    for item[index] in message.content: TextInput {
                        font-size: FontSettings.body.font-size + item.font-size-mul;
                        font-weight: FontSettings.body.font-weight;
                        text: item.data;
                    }
                }
            }
        }
    }
}

export component ChatMessageInputView {
    pure callback send-message(msg: string);
    HorizontalLayout {
        input-text := TextEdit {
            font-size: FontSettings.body.font-size;
            //  Valid units are: %, phx, px, cm, mm, in, pt, rem, s, ms, deg, grad, turn, rad
            preferred-height: 3 * self.font-size * 2 + 0.0769rem;
            wrap: word-wrap;
        }

        Button {
            text: "Send";
            clicked => {
                root.send-message(input-text.text);
                input-text.text = "";
            }
        }
    }
}

export component ChatView {
    preferred-height: 100%;
    preferred-width: 100%;
    forward-focus: focus-scope;
    focus-scope := FocusScope { }

    Rectangle {
        background: Palette.background;
        VerticalLayout {
            ChatMessageListView { }

            ChatMessageInputView {
                send-message(msg) => {
                    ChatViewAdapter.message(msg);
                }
            }
        }
    }
}
