export enum ChatGroupItemType {
    /// содержит другие группы
    Container,
    /// группа с чатом
    Message,
}

export struct ChatGroupItem {
    /// идентификатор текущего узла
    uid: string,
    /// уровень в иерархии
    level: int,
    /// подпись узла
    title: string,
    /// количество событий у текущего узла
    notifies: int,
    // содержит вложенные узлы
    has-children: bool,
    // открыт
    is-expanded: bool, 
    // листовой узел, внутри него нет потомков
    is-leaf: bool,
    /// иконка узла
    icon: image,
    /// тип группы
    type: ChatGroupItemType,
}

export global ChatGroupsAdapter {
    in-out property <[ChatGroupItem]> groups: [
        {
            title: "All",
            uid: "52c6c659-4b8a-4629-8402-355215fd4607",
            level: 0,
            has-children: true,
            is-leaf: false,
            is-expanded: true,
            notifies: 21
        },
        {
            title: "Chats",
            uid: "e1923a72-5380-4e01-856e-9f12c1402697",
            level: 1,
            has-children: true,
            is-leaf: false,
            is-expanded: true,
            notifies: 21
        },
        {
            title: "Новости", 
            uid: "934bc85d-0f04-4c51-8ba8-87cac576a0aa", 
            level: 2,
            has-children: false, 
            is-leaf: true, 
            is-expanded: false, 
            notifies: 10
        },
        {
            title: "РИА Новости", 
            uid: "396d8292-3382-4ee9-a4c9-2fd09662ecce", 
            level: 3,
            has-children: false, 
            is-leaf: true, 
            is-expanded: false, 
            notifies:5
        },       
        {
            title: "Инвестиции", uid: "980c3cc5-5a38-46b1-8936-13268d5ef3d6", 
            level: 1,
            has-children: true, 
            is-leaf: false, 
            is-expanded: true, 
            notifies: 6 
        },       
        {
            title: "Bonds",
            uid: "980c3cc5-5a38-46b1-8936-13268d5ef3d6",
            level: 2,
            has-children: false,
            is-leaf: true,
            is-expanded: true
        },
        {
            title: "Voices",
            uid: "bba5188d-2d7a-47df-ada1-b7839ee30f15",
            level: 0,
            has-children: true,
            is-leaf: false,
            is-expanded: true
        },
        {
            title: "Voice channel 1",
            uid: "91dafa45-c6a2-4d7f-9e29-57751820a032",
            level: 1,
            has-children: false,
            is-leaf: true,
            is-expanded: false
        },
        {
            title: "Channels",
            uid: "444257c4-bb60-4c66-a73f-a6c6696bd420",
            level: 0,
            has-children: true,
            is-leaf: false,
            is-expanded: false
        },
    ];
    in-out property <int> selected-group;
}
